help(Continuous-integration): re-organize the section
bump-sh/docs pull request #150
Opened 2023-11-30 11:39 UTC by paulRbr

This PR contains multiple changes:
- Re-organize (and rename) the previously named “Continuous Integration” section to the new “Integrate Bump.sh with your workflow”
- Re-write the index page to clarify the index of this section
- Move the CLI related page inside this section
- Backport recent changes from the Github-Action repository `README` (suggested by Phil Sturgeon)
- Add a new dedicated page to talk a bit about our API in this section

2023-11-30 14:58 UTC, jayk-u reviewed
Thanks a lot, @paulRbr :bow:

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/api.md
> +If neither the [Github-Action](/help/continuous-integration/github-actions/) or the [CLI](/help/continuous-integration/cli/) are sufficient for you, please read this page to discover what you can do
Is there any reason that could lead an user to go with the API? We could use that here, instead of the negative form?

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/api.md
> +- [List existing branches](https://developers.bump.sh/operation/operation-get-docs-parameter-branches) of your documentation
```suggestion
- [List existing branches](https://developers.bump.sh/operation/operation-get-docs-parameter-branches) of your documentation.
```

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/api.md
> +- [Fetch information of an existing Hub](https://developers.bump.sh/operation/operation-get-hubs-parameter) including the list of APIs it contains
```suggestion
- [Fetch information of an existing Hub](https://developers.bump.sh/operation/operation-get-hubs-parameter) including the list of APIs it contains.
```

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/github-actions.md
> +Bump.sh helps you build a branded single source of truth, cataloging all your APIs. We’ve created the reference point for teams consuming and building APIs, no matter which technology they rely on.
Not sure about that part. I don't think that we should promote Bump.sh at this step.

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/github-actions.md
> +This is the most common worklow that we [recommend using](https://help.bump.sh/continuous-integration#integrate-with-your-ci), which will create two steps in your automation flow: a validation & diff
```suggestion
This is the [recommend workflow](https://help.bump.sh/continuous-integration#integrate-with-your-ci), which will create two steps in your automation flow: a validation & diff step on code reviews, followed by a deployment step on merged changes.
```

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/github-actions.md
> +### Diff on Pull Requests only
```suggestion
### Diff on pull requests only
```

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/github-actions.md
> +If you only want to have API diff posted on pull requests use this workflow:
```suggestion
If you only want to have API diff posted on pull requests, use this workflow:
```

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/github-actions.md
> +Everyone interacting in the Bump `github-action` project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/bump-sh/github-action
```suggestion
Everyone interacting in the Bump.sh `github-action` project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/bump-sh/github-action/blob/master/CODE_OF_CONDUCT.md).
```

2023-11-30 14:58 UTC, jayk-u commented on src/_help/continuous-integration/index.md
>  Here, we are presenting the process recommended to our customers, but feel free to adapt it to your own workflow/requirements.
```suggestion
Here, we are presenting the process recommended to our users, but feel free to adapt it to your own workflow/requirements.
```

2023-12-04 09:17 UTC, ChristopheDujarric requested changes

2023-12-05 11:45 UTC, merged