golang guide with huma
bump-sh/docs pull request #157
Opened 2023-12-15 11:32 UTC by philsturgeon

2023-12-15 12:25 UTC, ChristopheDujarric requested changes

2023-12-15 12:25 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/go.md
> +[Huma](https://fastapi.tiangolo.com/) is a Golang framework that allows you to create APIs, and automatically generates their documentation, based on the OpenAPI specification.
```suggestion
[Huma](https://huma.rocks/) is a Golang framework that allows you to create APIs, and automatically generates their documentation, based on the OpenAPI specification.
```

2023-12-15 12:25 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/go.md
> +title: Deploying docs from FastAPI
```suggestion
title: Deploying docs from Huma
```

2023-12-15 12:25 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/go.md
> +title: Deploying docs from FastAPI
I'd also rename the file to `src/_guides/bump-sh-tutorials/huma.md`

2023-12-15 12:25 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/go.md
> +If for any reason you are unable to download that `openapi.yaml` from a URL despite being able to access it, it;s likely some odd network proxy settings on your machine or wifi. Grab it directly with
```suggestion
If for any reason you are unable to download that `openapi.yaml` from a URL despite being able to access it, it's likely some odd network proxy settings on your machine or wifi. Grab it directly with wget or similar.
```

2023-12-15 18:42 UTC, philsturgeon commented
Sorry that was sloppy. Merged all that, and will get focused on the bigger and better guides suggested.

2023-12-18 12:54 UTC, ChristopheDujarric approved these changes

2023-12-18 12:55 UTC, merged