Try it with Bruno and Postman
bump-sh/docs pull request #223
Opened 2024-04-29 12:54 UTC by philsturgeon

2024-05-13 10:05 UTC, ChristopheDujarric requested changes
Very cool, thanks @philsturgeon !

Only one small typo to fix. Can you also please update the filename to `2024-05-13-try-requests-in-postman.md` to better reflect the latest update?

2024-05-13 10:05 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/2024-04-28-try-requests-in-postman.md
> +It's possibly sat in the root of your repository, but if you're not sure, you can look at yor `.github/workflows/bump.yml` and see where the deploy command is looking for the `file: {filename}`.
```suggestion
It's possibly sat in the root of your repository, but if you're not sure, you can look at your `.github/workflows/bump.yml` and see where the deploy command is looking for the `file: {filename}`. 
```

2024-05-14 07:44 UTC, philsturgeon commented
@ChristopheDujarric good spot! I've done that and also added a bunch of Alt tags to the images.

2024-05-14 07:55 UTC, ChristopheDujarric commented
Thanks @philsturgeon !

A helpful resource, for sure!

2024-05-14 07:55 UTC, merged