Tutorial: Try it with Insomnia
bump-sh/docs pull request #237
Opened 2024-05-27 17:21 UTC by philsturgeon

2024-06-04 07:42 UTC, ChristopheDujarric requested changes
Thanks @philsturgeon ! Just a few minor suggestions.

2024-06-04 07:47 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/2024-05-14-try-requests-in-insomnia.md
can you also please update the filename to reflect the last update date?

2024-06-04 10:44 UTC, philsturgeon commented on src/_guides/bump-sh-tutorials/2024-05-14-try-requests-in-insomnia.md
> +Doing this for each operation is not ideal, but the Insomnia team have been notified about the error and hopefully this will be resolved soon.
Linked to the bug report.

2024-06-04 11:37 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/2024-05-14-try-requests-in-insomnia.md
> +Insomnia supports the idea of Environments, which means you can have one for "Development", one for "Production", others for sandboxes, mock servers, etc. It will create an OpenAPI Env which is pre-p
OK, I see your point! Please forget what I wrote :D

2024-06-04 12:15 UTC, philsturgeon commented on src/_guides/bump-sh-tutorials/2024-05-14-try-requests-in-insomnia.md
> +    [![Run in Insomnia}](https://insomnia.rest/images/run.svg)](https://insomnia.rest/run/?label=Train%20Travel%20API&uri=https%3A%2F%2Fraw.githubusercontent.com%2Fbump-sh-examples%2Ftrain-travel-api
This is the button they generated, it looks fine, and it doesn't seem to break things, so I dunno if I should go changing it?

2024-06-04 12:21 UTC, paulRbr commented on src/_guides/bump-sh-tutorials/2024-05-14-try-requests-in-insomnia.md
> +    [![Run in Insomnia}](https://insomnia.rest/images/run.svg)](https://insomnia.rest/run/?label=Train%20Travel%20API&uri=https%3A%2F%2Fraw.githubusercontent.com%2Fbump-sh-examples%2Ftrain-travel-api
Indeed, that's the alt text displayed in case the image doesn't load. It's not so important you can leave it as is.

2024-06-10 13:59 UTC, ChristopheDujarric approved these changes

2024-06-10 13:59 UTC, merged