guide: microcks testing
bump-sh/docs pull request #275
Opened 2024-08-22 18:09 UTC by philsturgeon

2024-08-23 06:54 UTC, ChristopheDujarric commented
@philsturgeon the deploy preview failed. Could it be because of a need to rebase with #266 being merged?

2024-08-23 10:11 UTC, philsturgeon commented
THe branch is up to date with upstream its some other problem.

2024-09-02 13:29 UTC, ChristopheDujarric requested changes

2024-09-02 13:29 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/testing-with-microcks.md
> +> The Conformance index is a kind of grade that estimates how your API contract (a.k.a API description) is actually covered by the samples you’ve attached to it. We compute this index based on the nu
```suggestion
> The Conformance index is a kind of grade that estimates how your API contract (a.k.a API description) is actually covered by the samples you’ve attached to it. We compute this index based on the number of samples you’ve got on each operation, the complexity of dispatching rules of these operations and so on… It represents the maximum possible conformance score you may achieve if all your tests are successful.
```

2024-09-06 08:46 UTC, merged