guide: linting with vacuum
bump-sh/docs pull request #313
Opened 2024-12-30 11:21 UTC by philsturgeon

2024-12-30 17:26 UTC, philsturgeon commented
This is ready for review as far as content goes @ChristopheDujarric, but it's stuck waiting for a reply from Vacuum as the JUnit support is not complete enough to work with any of the GitHub Actions that handle "Test Results".

If we can get a new version released I'll make a decent demo of a change with errors being "annotated" by Vacuum in the files changed view, and get a summary on it, but I wanted to make sure you like the general direction of it whilst we wait.

2024-12-31 08:16 UTC, ChristopheDujarric requested changes
Great guide! It will definitely be useful, thanks Phil.

2024-12-31 08:16 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/api-linting-with-vacuum.md
> +Let's try running vacuum to see how the API does before we worry about any further integrations.
```suggestion
Let's try running Vacuum to see how the API does before we worry about any further integrations.
```

2024-12-31 08:16 UTC, ChristopheDujarric commented on src/_guides/bump-sh-tutorials/api-linting-with-vacuum.md
> +excerpt:
```suggestion
excerpt: Validate API definition files against rules and policies before releasing new versions in Bump.sh.
```

2025-01-06 19:08 UTC, daveshanley commented
I will update vacuum to fix the issues!

2025-01-06 19:59 UTC, daveshanley commented
> I will update vacuum to fix the issues!

https://github.com/daveshanley/vacuum/pull/599 
https://github.com/daveshanley/vacuum/releases/tag/v0.15.1

`vacuum` should now push out the JUnit report correctly.

Thank you so much for doing this work, I am honored. 

My only ask would be that I spell `vacuum` with a lowercase 'v'. This is specifically because thats how it's typed in the console. all my tools are lowercase. 

Thank you once again!

2025-01-07 14:31 UTC, daveshanley commented
> > My only ask would be that I spell `vacuum` with a lowercase 'v'. This is specifically because thats how it's typed in the console. all my tools are lowercase.
> 
> @daveshanley thank you for the fix, and of course we'll spell it however you like.
> 
> Getting the line number has been helpful, but if you can add the file="" too then we're cooking with biogas.
> 
> This is good enough to move the docs forward though, so @ChristopheDujarric please review at will. I'm "done"! :D

I can indeed add`file`, coming up shortly!

2025-01-07 15:45 UTC, daveshanley commented
Available in `v0.15.2`

https://github.com/daveshanley/vacuum/releases/tag/v0.15.2

2025-01-08 01:31 UTC, daveshanley commented
> Thanks a ton to both of you @philsturgeon and @daveshanley !
> 
> I'm very excited about this collaboration. We're fans of Vacuum and regularly advertise it to our customers. Having a guide dedicated to it made a lot of sense.
> 
> Looking forward to more stuff together!
> 
> We'll wait only for a week or so before merging and publishing this, as we want to give it the proper exposure in our editorial calendar.

Great to hear it! thank you, looking forward to it too. 

I use the train-travel spec as my default / boostrap spec in the openapi doctor. It's the first thing folks see!

https://pb33f.io/doctor/?

2025-01-13 10:13 UTC, paulRbr commented on src/_guides/bump-sh-tutorials/api-linting-with-vacuum.md
> +"on":
```suggestion
on:
```

For consistency with what's usually seen in the wild, I'd recommend to remove the quotes here :)

2025-01-13 10:16 UTC, paulRbr commented on src/_guides/bump-sh-tutorials/api-linting-with-vacuum.md
> +        if: success() || failure()
```suggestion
        if: always()
```

2025-01-13 10:17 UTC, paulRbr commented on src/_guides/bump-sh-tutorials/api-linting-with-vacuum.md
> +        if: success() || failure()
that might not be necessary so I clicked to fast you can ignore my previous comment!

2025-01-13 14:43 UTC, philsturgeon commented on src/_guides/bump-sh-tutorials/api-linting-with-vacuum.md
> +        if: success() || failure()
I've gone with what the junit result people have used but I dont much mind either way.

2025-01-30 14:02 UTC, ChristopheDujarric approved these changes

2025-01-30 14:32 UTC, merged