custom domain: update wording for clarity
bump-sh/docs pull request #66
Opened 2023-04-11 08:15 UTC by paulRbr

Follow-up to #65

2023-04-27 17:23 UTC, antlio commented on docs/help/custom-domains.md
> +Your docs are hosted on Bump.sh. However you can set a custom domain: visitors of your docs will then stay within your own name. For this, you'll use a CNAME.
What bothers you here? I don't feel like it is much clear, however maybe we could just be pragmatic and explain just the how?

```suggestion
While [Bump.sh](http://bump.sh/) hosts your docs using a bump.sh domain, you can also set a custom domain quickly by setting a given CNAME.
```

2023-04-28 07:50 UTC, vvenance requested changes

2023-04-28 07:50 UTC, vvenance commented on docs/help/custom-domains.md
>  4. Click **Update global settings**.
Can we add a screenshot of this ?

2023-12-15 12:44 UTC, ChristopheDujarric commented
Closing this one as many things have changed with Jay's last version of the product docs. Feel free to review the new texts and open a new PR if necessary.

2023-12-15 12:44 UTC, closed without merging